### ISSUE TITLE
Empty content-type cause error while trying to fetch Json

### ISSUE THREAD

**Issue by elranr** [skord/maxpanel#1]
ember.debug.js:28535 Error while processing route: servers.index Ember Data Request GET http://someserverip:8003/servers returned a 0
Payload (Empty Content-Type)
Error: Ember Data Request GET http://someserverip:8003/servers returned a 0
Payload (Empty Content-Type)

On servers page or any related MaxScale json request.

**Comment by skord** [comment]
Is this preceded by a net::ERR_CONNECTION_REFUSED? 

I'm going to try and update the docs today to provide a little more information on how to use this, and I'll be opening more GH issues so I can track what I need to do and document. 

Just off the top of my head, you'll want to make sure you have the MaxInfo service and JSON listener enabled, which is documented here: https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale/maxinfo-plugin/

You'll also want to make sure you've setup a MaxScale user on your DB as detailed here: https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale/setting-up-maxscale/ or you'll see all sorts of errors. 

There are some issues trying to run this directly against a MaxInfo plugin right now. My dev environment consists of a MariaDB instance, a MaxScale instance, and an Nginx proxy sitting in front of MaxInfo. Most notably, since MaxInfo doesn't support sending CORS headers, they have to be added. Hopefully I can square a lot of that away soon as I'll be devoting more time to this project.

**Comment by skord** [comment]
I opened up a shell in my MaxScale docker container running MaxScale 1.4.3 and did a GET on the servers resource: 

```
root@145459f41d0a:/var/log/maxscale# curl -X GET -I http://localhost:8003/servers
HTTP/1.1 200 OK
Date: Sat, 21 May 2016 10:34:28 GMT
Server: MaxScale(c) v.1.0.0
Connection: close
Content-Type: application/json
```

Sure enough, the content type is there.

**Comment by skord** [comment]
This project now consumes the [skord/maxjsonapi](https://github.com/skord/maxjsonapi) project as it's API endpoint instead of talking with maxinfo directly. That project proxies requests to maxinfo as well as interfaces with maxadmin to provide the ability to actually administrate Maxscale. Closing this issue because it's now out of date.
